[profile.default]
src = 'src'
out = 'out'
libs = ["dependencies"]
solc = "0.8.25"
auto_detect_remappings = false
remappings = [
    "@octant-core/=dependencies/octant-v2-core/src/",
    "src/core/=dependencies/octant-v2-core/src/core/",
    "src/errors.sol=dependencies/octant-v2-core/src/errors.sol",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.3.0/contracts/",
    "@tokenized-strategy/=dependencies/tokenized-strategy-3.0.4/src/",
    "@tokenized-strategy-periphery/=dependencies/tokenized-strategy-periphery-3.0.2/",
    "forge-std/=dependencies/forge-std-1.11.0/src/"
]


[soldeer]
recursive_deps = true

[dependencies]
forge-std = { version = "1.11.0" }
tokenized-strategy = { version = "3.0.4", git = "https://github.com/yearn/tokenized-strategy", tag = "v3.0.4" }
tokenized-strategy-periphery = { version = "3.0.2", git = "https://github.com/yearn/tokenized-strategy-periphery", tag = "v3.0.2" }
"@openzeppelin-contracts" = { version = "5.3.0", git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v5.3.0" }


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
